"""added token usage, token count information for messages

Revision ID: 3155412d54f4
Revises: 49afb9deb4cd
Create Date: 2025-01-08 13:48:16.532960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3155412d54f4'
down_revision: Union[str, None] = '49afb9deb4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_terminal_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('token_usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usage_record_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_record_id')
    )
    op.create_table('ai_terminal_conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_terminal_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('step_conversation_messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('step_conversation_messages', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_conversation_messages', 'cost')
    op.drop_column('step_conversation_messages', 'token_count')
    op.drop_table('ai_terminal_conversation_messages')
    op.drop_table('token_usage_records')
    op.drop_table('ai_terminal_conversations')
    # ### end Alembic commands ###
