"""added llm model for conversation, and token usage

Revision ID: 927c2bd09b3e
Revises: 3155412d54f4
Create Date: 2025-01-09 17:25:28.960272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927c2bd09b3e'
down_revision: Union[str, None] = '3155412d54f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_conversations', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('token_usage_records', sa.Column('llm_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_usage_records', 'llm_model')
    op.drop_column('step_conversations', 'llm_model')
    # ### end Alembic commands ###
