version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    ports:
      - "5900:5900"
      - "9223:9223"
      - "8001:8000"
    environment:
      - DISPLAY=:99
    volumes:
      # Mount only autobyteus-server source code
    restart: unless-stopped
