FROM autobyteus-base:latest

# Copy supervisor configuration and entrypoint script
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY entrypoint.sh /entrypoint.sh

RUN dos2unix /entrypoint.sh && \
    chmod +x /entrypoint.sh

WORKDIR /home/vncuser/workspace

EXPOSE 5900 9223 8000

ENTRYPOINT ["/entrypoint.sh"]
